sharpdx/SharpDX

- Source/SharpDX.D3DCompiler/ShaderBytecode.cs
Hello,
I noticed on last build the Compile function was checking that only FX profile could have a null entry point.
Since Library profile is also allowed to have no profile, I added the condition in there
Thanks
> [SharpDX.D3DCompiler] Small issue with library profile

- Source/SharpDX.Desktop/MessageFilterHook.cs
MessageFilterHook made public, I've used it for different things (it used to be public in SharpDX 2.6.3).
Is there any reason to hide it?
> MessageFilterHook class is now public

- Source/SharpDX.Mathematics/Matrix.cs
Solves #700.
Use specialized method to calculate perspective projection matrix when given FOV.
Correctly handles the situation in which distance to near plane is 0,
given FOV rather than a rectangle.
> Solves #700

- Source/SharpDX.XAudio2/Mapping-xaudio2.xml
> Fixed Issue #709 'XAudio2 SourceVoice.State.SamplesPlayed always returns 0 in 64-bit configurations'.

- Source/SharpDX.XAudio2/EngineShadow.cs
SharpDX.XAudio2.EngineShadow.EngineVtbl.OnProcessingPassEndImpl was incorrectly calling callback.OnProcessingPassStart() instead of callback.OnProcessingPassEnd().
> Fixed XAudio2.ProcessingPassStart event being invoked instead of ProcessingPassEnd.

- Source/SharpDX.Direct3D11/Device.cs
- Source/SharpDX.Direct3D11/Mapping.xml
- Source/SharpDX.Direct3D12/Mapping.xml
Added support for Direct3D11On12 in the Direct3D11 library as suggested by @xoofx . Removed the old mapping in Drect3d12 which was unused.
There does exist an unresolved problem, but I'm not sure what's causing it as the program just crashes. The code below always crashes with no error when I attempt to create a bitmap from a wrappedresource. This code is entirely based off of a directx12 sample. Just so you know this is an unresolved problem, and as I'm not getting any error feedback therefore I'm not sure what to make of it.
```C#
_fact2D = (new SharpDX.Direct2D1.Factory2(SharpDX.Direct2D1.FactoryType.MultiThreaded, SharpDX.Direct2D1.DebugLevel.Error)).QueryInterface<Factory2D>();
_dev11 = Device11.CreateFromDirect3D12(_dev, SharpDX.Direct3D11.DeviceCreationFlags.BgraSupport | …
```
> Adding Direct3D11On12 Support in Direct3D11

- Source/SharpDX.RawInput/Device.cs
- Source/SharpDX.RawInput/HidInputEventArgs.cs
- Source/SharpDX.RawInput/KeyboardInputEventArgs.cs
- Source/SharpDX.RawInput/MouseInputEventArgs.cs
- Source/SharpDX.RawInput/RawInputEventArgs.cs
RawInputEventArgs (and thus also HidInputEventArgs, KeyboardInputEventArgs, and MouseInputEventArgs) now has a WindowHandle property that can be used to retrieve the handle of the window that received the raw input event.
> Added RawInputEventArgs.WindowHandle property

- Source/SharpDX.Direct3D11/DeviceContext.RasterizerStage.cs
Hi, after updating from 2.6.2 to 3.0.2, 
SharpDX.Direct3D11.DeviceContext.RasterizerStage.SetViewports( RawViewportF[] ) and SharpDX.Direct3D11.DeviceContext.RasterizerStage.SetScissorRectangles( RawRectangle[] )
now throw null reference exceptions if you pass in a null array. This pull request is a fix.
> Fix for null reference exception in DeviceContext.RasterizerStage

- Source/SharpDX.Direct3D12/Mapping.xml
Out modifier is incorrect.
ReadFromSubresourceは、C#側で作成したメモリ領域を渡し、その領域に書き込まれます。
そのため、pDstDataに設定されているOut修飾子は正しくない認識です。
現実装のコードを実行した場合、処理が終了しないか、AccessViolationException等が発生します。
> Fixed ReadFromSubresource

- Source/SharpDX/Multimedia/WaveFormatAdpcm.cs
Set default values to local `blockAlign` before assigning the value to the member field `this.blockAlign`.
Check `blockAlign` for invalid values and that it can be cast to `short/Int16`.
fix #791
> fix initialization of local blockAlign with default values. 

- Source/SharpDX.DirectInput/MouseState.cs
Fixed incorrect direct copying of returned button array bytes into C# Boolean array. According to this page, https://msdn.microsoft.com/en-us/library/windows/desktop/bb151897(v=vs.85).aspx, the data format states that the value of the byte will be 128 if the button is on and 0 if the button is off. By directly copying the byte value of 128 into a bool, an invalid Boolean is created which initially doesn't cause any problems, but will fail if you bitwise or the bool with true giving you a value of 129 which evaluates to false when compared to C# true (1). This error also existed in JoystickState in a past version and was fixed. The same error in MouseState was never fixed however.
> Fix button array bug in Update MouseState.cs

- Source/SharpDX.DirectComposition/Target.cs
This is method is the only way to create a Target in Windows 8, which doesn't have `DesktopDevice`. And this method is unfortunately missing.
> Add missing DirectComposition method to create Target from `Device`

- Source/SharpDX.Direct3D11/Device.cs
When `CreateWithSwapChain` method is used to create a device, it ends up in a native memory leak, when the device, and all its devices are disposed. This doesn't happen when the device and swap chains are created manually. 
Turns out, this happens due to the extra `AddRefs` that gets called internally. The extra unmanaged memory that ends up leaking can be worked around by casting to `IUnknown` and doing an extra manual release, on the device context. 
Incidentally, it happens to be so that the entire set of code that causes this leak in the first place, is totally redundant, since the `ImmediateContext` and the inner `Device` that are manually force initialized care of themselves already. So, simply removing the unnecessary code fixes this. 
PS: Is there any reason that this code is here …
> Fix: Memory leak for D3D11 device when `CreateWithSwapChain` is used

- Source/SharpDX/DataBuffer.cs
- Source/SharpDX/DataStream.cs
This change works around the .NET Native compiler bug by casting to (IntPtr).
I also noticed that DataBuffer had the same issue as DataStream which was fixed by b9f7519 so I applied the same fix to DataBuffer.
FWIW the code in question calls Interop.Fixed which throws NotImplementedException.
> The SharpDX commit b9f7519 caused the .NET Native compiler to crash.

- Source/SharpDX.Direct2D1/WIC/WICStream.cs
Fixed WicStream.Dispose to dispose of 'streamProxy' after calling base.Dispose to fix a crash in .NET Native when used with a MemoryStream in a multi-threaded image rendering test.
This change makes WicStream consistent with the behavior of SharpDX.MediaFoundation.ByteStream.
> Fixed WicStream.Dispose bug exposed by .NET Native

- Source/SharpDX/Utilities.cs
This is a fix for issues https://github.com/sharpdx/SharpDX/issues/828 and https://github.com/sharpdx/SharpDX/issues/806
The existing code used Marshal.PtrToStringUni(pointer, maxLength) method that did not terminate the string at first null char - see MSDN: https://msdn.microsoft.com/en-us/library/k4x4bfws(v=vs.110).aspx
This resulted in having Adapter description always 128 chars long.
The proposed fix uses Marshal.PtrToStringUni(pointer) method (without maxLength parameter) that correctly terminates the string - see MSDN: https://msdn.microsoft.com/en-us/library/dyf0tzy4(v=vs.110).aspx
The fixed code also truncates the string if it is larger than the specified maxLength.
> Fixed AdapterDescription.Description text with fixing PtrToStringAnsi and PtrToStringUni methods

- Source/SharpDX.Mathematics/RectangleF.cs
Containment method for Vector2 of RectangleF is now exactly the same as for individual x and y values. for some reason it was excluding the right and lower border.
> RectangleF.Contains(Vector2) now includes right and lower border

- Source/SharpDX.Direct3D10/DeviceChild.cs
- Source/SharpDX.Direct3D11/DeviceChild.cs
This is a fix for Issue  #850.
Because portable .Net does not provide methods to convert string into ANSI encoded byte array (as proposed by OndrejPetrzilka), the solution is to continue using Marshal.StringToHGlobalAnsi and releasing it with  #Marshal.FreeHGlobal.
> Freeing allocated string in DebugName setter

- Source/SharpDX/Win32/Variant.cs
Added setter functionality to assign byte and sbyte values to a variant
type. This will correct the issue described in issue #787
> Updated variant.cs for issue #787

- Source/SharpDX.Direct3D12/GraphicsCommandList.cs
Hello, 
just added two convenience overloads on command list (to allow descriptor heaps and vertexbuffers to be set as params (which also allows to set a single heap more easily as well)
Thanks
> Overloads for SetDescriptorHeaps and SetVertexBuffers

- Source/SharpDX.Mathematics/Matrix3x2.cs
Matrix3x2.Multiply did not behave correctly when passing the same object to left or right argument and the result argument. With this change it follows the same pattern as Matrix.Multiply and Matrix3x3.Multiply.
> Matrix3x2.Multiply now behaves like other Matrix.Multiply functions

- Source/SharpDX.DirectComposition/SharpDX.DirectComposition.csproj
Correctly generate the SharpDX.DirectComposition package and don't overwrite the SharpDX.Direct3D9 package.
Fix #873
> Fix sharpdx.DirectComposition project metadata.

- Source/Tools/SharpGen/Model/CsBase.cs
Hello, this is a very small pull request, that fixes the path for setting include in code comments.
As it was wrong, visual studio was reporting more than 50k code comment warnings.
Thanks
Julien
> [SharpGen] Include path fix

- Source/Tools/SharpGen/RunGenerator.bat
> Remove Windows 10 SDK requirement from the SharpGen batch script

- Source/SharpDX.Direct2D1/DirectWrite/FontFallback.cs
- Source/SharpDX.Direct2D1/DirectWrite/Mapping.xml
- Source/Tools/SharpGen/CppModel/CppStruct.cs
- Source/Tools/SharpGen/Generator/StructTransform.cs
- Source/Tools/SharpGen/Parser/CppParser.cs
From what we discussed in https://github.com/sharpdx/SharpDX/issues/896.
There are DirectWrite structs, such as [FontFallback1](https://msdn.microsoft.com/en-us/library/windows/desktop/jj126259(v=vs.85).aspx), that have ancestor structs, but the latter's fields were not written out for the former so we were seeing `AccessViolationException`s. https://github.com/sharpdx/SharpDX/commit/1ab7aa929e2e57c3b543f8b8d0ad790d5d3e607d should fix that.
https://github.com/sharpdx/SharpDX/commit/18cb55ae57df46adf84a1bf22548220f24493f96 provides a public wrapper for a method on DirectWrite's `FontFallback`.
> DirectWrite enhancements

- Source/SharpDX.Direct3D11/DeviceContext1.cs
- Source/SharpDX.Direct3D11/Mapping.xml
Hello, 
This pull request fixes the mapping for clearview (which expects float[4] as per the documentation).
I also added a convenience overload that allows to use parameter values.
Thanks
Julien
> Fix ClearView mapping

- Source/SharpDX/ComObject.cs
@xoofx @rockhymas As discussed in https://github.com/sharpdx/SharpDX/issues/913
> Allow custom memory leak logging for client apps

- Source/SharpDX.D3DCompiler/ShaderBytecode.cs
This PR addresses two issues related to compiling ShaderBytecode:
* When `ShaderBytecode.Compile` failed, it never returned an error result code or threw an exception, even when `Configuration.ThrowOnShaderCompileError` was `true`. This is because it assumed that `D3D.Compile2` throws an exception on failure, which is not the case. This PR adds explicit error handling by checking the result code. This fixes #695.
* When using `ShaderBytecode.CompileFromFile`, the error messages always refer to the source file as `unknown`. Passing along the `fileName` fixes this.
> Improve error reporting in ShaderBytecode.Compile/CompileFromFile

- Source/Tools/SharpPak/SharpPak.csproj
without the fix, SharpPak crashes because it can't load the correct version of Mono.Cecil (it uses both 9.5.0 and 9.6.0)
> fixed binding redirects in SharpPak

- Source/SharpDX.Direct2D1/DeviceContext5.cs
- Source/SharpDX.Direct2D1/Mapping-direct2d1.xml
- Source/SharpDX.Direct2D1/SvgAttribute.cs
- Source/SharpDX.Direct2D1/SvgDocument.cs
- Source/SharpDX.Direct2D1/SvgElement.cs
Hello, 
this pull request adds many functions to improve the Svg support in Direct2D:
* Create Svg Document from Stream 
* Easier to clone svg atribute
* Overloads for every possible type for Get/Set Attribute value (that includes a Generic Getter for attribute derived com objects, such as path data)
One part I'm curious of, set overloads work fine, but maybe instead (or on top of) of get overloads (with out parameters), can have "GetColorAttribute", "GetValueAttribute" and so on.
Thanks
> Direct2D and SVG

- Source/SharpDX.XInput/Mapping.xml
Change GamepadButtonFlags mapping from type short to ushort to fix issue with Y flag being incorrectly mapped. Y flag is currently mapped to Y = short.MinValue. It should be mapped to Y = 32768. I think changing the type to ushort should correctly remap the enumeration.
Edit: Although I think this behaviour of the code generator may indicate a problem with how it handles the mapping of flags enumerations. It shouldn't try to wrap the enumeration - if that's what it's doing. But that is beyond my ability to investigate, so I can only suggest that as a possible problem.
Edit : Apologies for the mess here, the correct type should be int, not ushort, as ushort isn't a supported type in the SharpDX build software for the enumeration. I've submitted a fresh pull request. But not sure if I …
> Update Mapping.xml - fix GamepadButtonFlags

- Source/SharpDX.DXGI/Mapping.xml
- Source/SharpDX.DXGI/OutputDuplication.cs
AquireNextFrame returning a non-Ok result is expected behaviour
when submitting a short timeout, and shouldn't result in a (slow)
exception.
Should help fixing #861, #839, and #515.
> TryAquireNextFrame-API for Desktop-Duplication-API.

- Source/SharpDX.MediaFoundation/Mapping-core.xml
- Source/SharpDX.MediaFoundation/SinkWriter.cs
A fix for `SinkWriter.GetStatistics`. It's broken at the moment as the `cb` field of `SinkWriterStatistics` needs to be set to the size of the struct in bytes before passing it to the method. This is described in the documentation:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd374650(v=vs.85).aspx
I'm not sure if my code represents best practice, so let me know if there's a better way to fix this than what I've done and I'll resubmit it.
> [MediaFoundation] SinkWriter.GetStatistics fix

- Source/SharpDX.Direct3D11/DeviceContext.StreamOutputStage.cs
Just a small one, but instead of throwing exception in SetTarget, we should unset the slot instead (as per all other resource bindings)
Thanks
> [Direct3D11] SetTarget, allow null

- Source/SharpDX.DXGI/DXGIDebug.cs
- Source/SharpDX.DXGI/DXGIDebug1.cs
- Source/SharpDX.DXGI/Mapping.xml
This fixes #1020 
This should please users complaining about #972 
It **will** break the few existing lines of code that are already using the newly added `DXGI.Debug` stuff.
On the other hand, not merging this PR will break **all** existing code that both is `using System.Diagnostics.Debug` and `using SharpDX.DXGI` at the same time.
> Renamed DXGI.Debug to DXGI.DXGIDebug

- Source/SharpDX.MediaFoundation/MediaAttributes.cs
After the change to make `IUnknown` map to `IUnknown` instead of `ComObject`, the Set call here recursively called `Set<ComObject>` instead of the non-generic `Set` method that takes `IUnknown`.
> Fix #1039.

- Source/SharpDX.Direct2D1/DirectWrite/ColorGlyphRunEnumerator.cs
- Source/SharpDX.Direct2D1/DirectWrite/Mapping.xml
Correctly implement ColorGlyphRunEnumerator's GetCurrentRun method as a GetCurrent() method. Fixes #1012.
> Correctly implement ColorGlyphRunEnumerator's GetCurrentRun method

- Source/Directory.build.props
- Source/SharpDX.Direct2D1/Mapping-direct2d1.xml
- Source/SharpDX.Direct3D12/ShaderBytecode.cs
Related to issue #1048
Fixes #1053
> Fix codegen with SharpGenTools

- Source/SharpDX.Mathematics/Matrix.cs
when calling matrix with ToString("F4", cultureInfo) the string "F4" was returned. now calling same overload as vectors do.
> Wrong overload used in ToString(format, IFormatProvider)

- Source/Directory.build.props
- Source/SharpDX.Direct2D1/WIC/ColorContextsHelper.cs
- Source/SharpDX.Direct3D11/Mapping.xml
- Source/SharpDX/Direct3D/Mapping.xml
This should fix all of the remaining regressions in the generated code from SharpGenTools.
Fixes #1048.
> Fix SharpGenTools Regressions

- Source/SharpDX.MediaFoundation/MediaAttributes.cs
Fix type check in MediaAttributes as mentioned in #1039.
> Fix type check in MediaAttributes to work correctly with an interface type.

- Source/SharpDX.Direct2D1/Mapping-direct2d1.xml
Some of the D2D1 result codes are still missing. This PR adds back the ones that are defined in `winerror.h`.
> Add missing D2D1 Result Codes.

- Source/SharpDX.XAudio2/MasteringVoice.cs
- Source/SharpDX.XAudio2/Voice.cs
- Source/SharpDX.XAudio2/XAudio2.cs
- Source/SharpDX.XAudio2/XAudio29Functions.cs
- Try to create XAudio 2.9 even on Windows10 desktop.
- Map Volume property to Voice.
- Handle CoInitializeEx on Desktop platforms (dotnet/corert#6046).
> XAudio improvements

- Source/SharpDX.XAudio2/X3DAudio/Emitter.cs
When **X3dAudio.Calculate** method is invoked for an emitter with a non-null **Cone**, an exception is raised indicating an invalid memory access.
To solve this, I have removed the **Marshal.FreeHGlobal(ConePointer)** invocation from the **Emitter.__Native.__MarshalFree()** method. That causes the exception, seeing that this structure is always allocated in the stack and no memory is allocated using **Marshal.AllocHGlobal**.
> Remove Marshal.FreeHGlobal over ConePointer to avoid native exception
