sharpdx/SharpDX

- Source/SharpDX.Direct2D1/BitmapProperties1.cs
- Source/SharpDX.Direct2D1/LayerParameters.cs
- Source/SharpDX.Direct2D1/LayerParameters1.cs
- Source/SharpDX.Direct2D1/Mapping-direct2d1.xml
Hello,
I fixed bug #584 .
Thanks.
> [SharpDx.Direct2D] Fix bug #584 and change maping

- Source/SharpDX.MediaFoundation/Activate.cs
- Source/SharpDX.MediaFoundation/MediaTypeHandler.cs
- Source/SharpDX.MediaFoundation/PresentationDescriptor.cs
- Source/SharpDX.MediaFoundation/SharpDX.MediaFoundation.csproj
- Source/SharpDX.MediaFoundation/VideoFormatGuids.cs
Hello,
another small pull request, just some overloads to allow ActivateObject and GetMediaType so they work as function without the need for out parameters.
Thanks
Julien
> Mediafoundation additions

- Source/SharpDX.Animation/SharpDX.Animation.csproj
- Source/SharpDX.Animation/SharpDX.Animation.nuspec
Hi,
please publish nuget packet.
Thanks.
> [Animation] add nuspec (#631)

- Source/SharpDX/Diagnostics/ObjectTracker.cs
Resolves #676 , see it for justification.
> Object tracker custom stack provider

- Source/SharpDX/Mathematics/Interop/RawBool.cs
- Source/SharpDX/Mathematics/Interop/RawColor3.cs
- Source/SharpDX/Mathematics/Interop/RawInt3.cs
- Source/SharpDX/Mathematics/Interop/RawInt4.cs
- Source/SharpDX/Mathematics/Interop/RawMatrix3x2.cs
- Source/SharpDX/Mathematics/Interop/RawPlane.cs
- Source/SharpDX/Mathematics/Interop/RawPoint.cs
- Source/SharpDX/Mathematics/Interop/RawQuaternion.cs
- Source/SharpDX/Mathematics/Interop/RawVector2.cs
- Source/SharpDX/Mathematics/Interop/RawVector3.cs
- Source/SharpDX/Mathematics/Interop/RawVector4.cs
> Support for Raw* Mathematics constructors for better coding experience.

- Source/SharpDX.MediaFoundation/Mapping-core.xml
- Source/SharpDX/Mathematics/Interop/RawBool.cs
- Source/SharpDX/Mathematics/Interop/RawColor3.cs
- Source/SharpDX/Mathematics/Interop/RawInt3.cs
- Source/SharpDX/Mathematics/Interop/RawInt4.cs
- Source/SharpDX/Mathematics/Interop/RawMatrix3x2.cs
- Source/SharpDX/Mathematics/Interop/RawPlane.cs
- Source/SharpDX/Mathematics/Interop/RawPoint.cs
- Source/SharpDX/Mathematics/Interop/RawQuaternion.cs
- Source/SharpDX/Mathematics/Interop/RawVector2.cs
- Source/SharpDX/Mathematics/Interop/RawVector3.cs
- Source/SharpDX/Mathematics/Interop/RawVector4.cs
> Mfp create media player fix

- Source/SharedAssemblyInfo.cs
- Source/SharpDX.Desktop/Documentation/CodeComments.xml
- Source/SharpDX.DirectManipulation/Properties/AssemblyInfo.cs
> Add lostfile and small change

- Source/SharpDX.Direct3D11/Device.cs
remove addreference on the Device because Context does not release them
> Leak Device

- Source/SharpDX.Mathematics/Collision.cs
- Source/Tests/SharpDX.Tests/MathCollisionTest.cs
- Source/Tests/SharpDX.Tests/SharpDX.Tests.csproj
> [Mathematics] fix bug in Collision.ClosestPointPointTriangle()

- Source/SharpDX.DXGI/Mapping.xml
- Source/SharpDX.DXGI/SwapChain1.cs
…so that the application can check whether the window is occluded. This should resolve #746.
> SwapChain.Present and SwapChain1.Present now return their result codes.

- .editorconfig
- Source/SharpDX.Direct3D11/Mapping.xml
- Source/SharpDX.Direct3D12/Mapping.xml
Mapping improvements for ID3D11On12Device and Direct3D12 ResourceStates.
> Mapping improvements

- Source/SharpDX.Direct3D12/GraphicsCommandList.cs
GraphicsCommandList improvements and add better BeginEvent and SetMarker methods.
> GraphicsCommandList improvements

- Source/SharpDX.Mathematics/BoundingSphere.cs
seems to be a copy/paste error
> fixed help text BoundingBox -> BoundingSphere

- Source/SharpDX.Direct3D12/StaticSamplerDescription.cs
Hello, this is a simple addition, to allow to create a static sampler from an existing SamplerStateDescription.
Thanks
Julien
> StaticSamplerDescription

- Build/SharpDXGen.proj
> Add Rebuild target to SharpDXGen

- Source/SharpDX.MediaFoundation/VideoFormatGuids.cs
- Source/SharpDX/Multimedia/FourCC.cs
> Added IFormattable to FourCC to implement fix for FromFourCC.

- Source/SharpDX.D3DCompiler/FunctionLinkingGraph.cs
Hello, 
very small one, just adding overload to GenerateHlsl so we can retrieve it directly as a string.
Thanks
> Small overload to GenerateHlsl method

- Source/SharpDX.MediaFoundation/Mapping-core.xml
Updated Mapping-core to remove unsupported functions that cause a
failure during certification on the windows store.
The multiple commits are because I was having an account issue...
> Removed addtional methods that are unsupported on the windows store.

- Source/SharpDX.Mathematics/BoundingBox.cs
- Source/SharpDX.Mathematics/Vector2.cs
- Source/SharpDX.Mathematics/Vector3.cs
Hello, just a small pull request since I use those as extension methods almost everywhere, just thought this would benefit everyone:
* Abs for Vector2 / Vector3
* Some properties for bounding box (size/ center)
Thanks 
Julien
> Some new math functions

- Source/SharpDX.MediaFoundation/VideoFormatGuids.cs
As specified in #909, this pull request adds missing formats manually again (those are not changing ever so often, but I guess will need to look on updates if a new one pops in).
> [SharpDX.MediaFoundation] VideoFormatGuids

- Build/SharpDX.targets
This allows adding the SharpDX projects to a custom solution
> SharpDX.targets is now project-relative

- Source/SharpDX.Direct3D11/Mapping.xml
> [Direct3D11] Sets pDstData in ReadFromSubresource as in parameter

- Source/SharpDX.XInput/Mapping.xml
> Fix XInput GamepadButtonFlags issue.

- Source/SharpDX.DirectComposition/AffineTransform2DEffect.cs
- Source/SharpDX.DirectComposition/ArithmeticCompositeEffect.cs
- Source/SharpDX.DirectComposition/BlendEffect.cs
- Source/SharpDX.DirectComposition/BrightnessEffect.cs
- Source/SharpDX.DirectComposition/ColorMatrixEffect.cs
- Source/SharpDX.DirectComposition/CompositeEffect.cs
- Source/SharpDX.DirectComposition/Device.cs
- Source/SharpDX.DirectComposition/Device3.cs
- Source/SharpDX.DirectComposition/GaussianBlurEffect.cs
- Source/SharpDX.DirectComposition/HueRotationEffect.cs
- Source/SharpDX.DirectComposition/LinearTransferEffect.cs
- Source/SharpDX.DirectComposition/Mapping.xml
- Source/SharpDX.DirectComposition/SaturationEffect.cs
- Source/SharpDX.DirectComposition/ShadowEffect.cs
- Source/SharpDX.DirectComposition/TableTransferEffect.cs
- Source/SharpDX.DirectComposition/TurbulenceEffect.cs
Add per issue #970
Make device classes public (as per generated code)
Add a protected empty constructor on Device2 (to allow override for Device3)
Add Device3 and All effects that can be constructed by it
> [DirectComposition] Support for Device3 and effects

- Source/SharpDX/DataStream.cs
As discussed in https://github.com/sharpdx/SharpDX/issues/996
> Added missing finalizer

- Source/SharpDX.MediaFoundation/Mapping-core.xml
Resolves issue described here: https://github.com/sharpdx/SharpDX/issues/521
> [MediaFoundation] Fixed CreateVideoSampleFromSurface

- Source/SharpDX.Direct2D1/DirectWrite/Factory2.cs
- Source/SharpDX.Direct2D1/DirectWrite/Mapping.xml
> Try API for TranslateColorGlyphRun

- Source/SharpDX.DXGI/Mapping.xml
- Source/SharpDX.Direct3D11/Mapping.xml
- Source/SharpDX.Direct3D12/Device.cs
- Source/SharpDX.Direct3D12/Mapping.xml
- Map D3D12_RLDO_FLAGS to ReportingLevel.
- Remove reserved ID3D11CommandList::GetContextFlags
> Various improvements

- Source/SharpDX.XInput/GamepadButtonFlags.cs
- Source/SharpDX.XInput/Mapping.xml
> Correctly map XInput GamepadButtonFlags.

- Source/Directory.build.props
- Source/SharpDX.Direct2D1/WindowRenderTarget.cs
> Update SharpGenTools.Sdk to 1.1.1-ci465

- Source/Directory.build.props
> Upgrade to SharpGenTools 1.1.1-ci466.

- Source/SharpDX.Direct2D1/DirectWrite/ColorGlyphRunEnumerator1.cs
- Source/SharpDX.Direct2D1/DirectWrite/Mapping.xml
> Update ColorGlyphRunEnumerator mapping.

- Source/SharpDX/SharpDX.csproj
> Fix SharpDX.csproj not generating documentation.

- Readme.md
- Source/Directory.build.props
- build.cmd
Cleans up shared files between projects and simplifies the build process. Also updates the readme to accurately reflect the required VS components.
> Simplify build process

- Readme.md
- Source/Directory.build.props
- Source/Mapping.xml
- Source/SharpDX.DXGI/Mapping.xml
- Source/SharpDX.Direct3D11/Mapping.xml
- Source/SharpDX.Direct3D12/Mapping.xml
- global.json
This PR does:
- Update to 10.0.17134.0 Windows SDK.
- Update MSBuild.Sdk.Extras to 1.6.55.
- Update SharpGenTools.Sdk to 1.1.2.
> Update to 10.0.17134.0 Windows SDK.

- Source/Directory.build.props
- appveyor.yml
- version.json
- Add support for Nerdbank.GitVersioning and move version to 4.2.1-beta0
> GIT Versioning

- Source/SharpDX.Direct3D12/Device4.cs
- Source/SharpDX.Direct3D12/Mapping.xml
- New D3D12 Device4 improvements, map correctly CreateCommandList1, CreateHeap1 and CreateProtectedResourceSession.
> D3D12 improvements

- Source/SharpDX.Direct3D11/Device.cs
- Source/SharpDX.Direct3D11/Mapping.xml
- Source/SharpDX.Direct3D12/Device.cs
- Source/SharpDX.Direct3D12/Device5.cs
- Source/SharpDX.Direct3D12/Mapping.xml
- Initial ID3D12Device5::CreateStateObject support.
- Improve some D3D12_MESSAGE_ID enum names.
- D3D11 Add support for FeatureDataD3D11Options5 mapping.
> More Improvements

- Source/SharpDX.Direct3D12/BuildRaytracingAccelerationStructureInputs.cs
- Source/SharpDX.Direct3D12/Mapping.xml
Correctly marshal D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS
> D3D12 Raytracing
